// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqw4CmYQsvt3iG0iQTY45qCoJ_LQwj5hU',
    appId: '1:673291438053:web:034447ee79c77eae1a910c',
    messagingSenderId: '673291438053',
    projectId: 'flutter-semester-project',
    authDomain: 'flutter-semester-project.firebaseapp.com',
    storageBucket: 'flutter-semester-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPUn9WZyZ2X-q4KXOzUBY4QEpByovjyAU',
    appId: '1:673291438053:android:9fa436426ac5a7241a910c',
    messagingSenderId: '673291438053',
    projectId: 'flutter-semester-project',
    storageBucket: 'flutter-semester-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBumRow5RvXhNOsejzWbe0AGe2XiVMbT1k',
    appId: '1:673291438053:ios:ae54252c14a8ac171a910c',
    messagingSenderId: '673291438053',
    projectId: 'flutter-semester-project',
    storageBucket: 'flutter-semester-project.appspot.com',
    iosClientId: '673291438053-maqm8ishj6m0b8890g4m9j07kvocodm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBumRow5RvXhNOsejzWbe0AGe2XiVMbT1k',
    appId: '1:673291438053:ios:ae54252c14a8ac171a910c',
    messagingSenderId: '673291438053',
    projectId: 'flutter-semester-project',
    storageBucket: 'flutter-semester-project.appspot.com',
    iosClientId: '673291438053-maqm8ishj6m0b8890g4m9j07kvocodm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
